In [33]:
import numpy as  np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV

In [34]:
df = pd.read_csv('housing.csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [35]:
df = df.drop(['ocean_proximity','longitude','latitude','population'],axis = 1)
df.head()

,housing_median_age,total_rooms,total_bedrooms,households,median_income,median_house_value
0,41.0,880.0,129.0,126.0,8.3252,452600.0
1,21.0,7099.0,1106.0,1138.0,8.3014,358500.0
2,52.0,1467.0,190.0,177.0,7.2574,352100.0
3,52.0,1274.0,235.0,219.0,5.6431,341300.0
4,52.0,1627.0,280.0,259.0,3.8462,342200.0

In [36]:
df['total_bedrooms']= df['total_bedrooms'].fillna(df['total_bedrooms'].mean())

In [37]:
x = df.drop(['median_house_value'],axis = 1)
y = df['median_house_value']

In [38]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=24)

In [39]:
std = StandardScaler()
x_train_scale = std.fit_transform(x_train)
x_test_scale = std.transform(x_test)

In [40]:
model = LinearRegression()
model.fit(x_train_scale,y_train)
y_pred = model.predict(x_test_scale)
print('r2_score:',r2_score(y_test,y_pred))

r2_score: 0.5535409315065491